<div
    class="dashboard-calendar"
    data-dashboard-calendar
>

    <button
        class="calendar-nav calendar-nav-previous"
        type="button"
        aria-label="Previous days"
        data-calendar-previous
    >
        ‹
    </button>

    <div
        class="calendar-view"
        data-calendar-view
    >
        {{-- Calendar content generated by JS --}}
    </div>

    <button
        class="calendar-nav calendar-nav-next"
        type="button"
        aria-label="Next days"
        data-calendar-next
    >
        ›
    </button>

</div>